jobs:
- name: (( concat "create-cluster-" config.cluster.name ))
  serial: true
  serial_groups:
  - (( grab config.cluster.name ))
  plan:
  - get: ci-resources
  - get: cluster-state
    trigger: true
    passed: [(( concat "delete-cluster-" config.cluster.name ))]
  - task: create-kubernetes-cluster
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: eirini/gcloud
          username: (( grab config.dockerhub.user ))
          password: (( grab config.dockerhub.password ))
      inputs:
        - name: ci-resources
      params:
        GCP_SERVICE_ACCOUNT_JSON: (( grab config.gcp.service-account-json ))
        CLUSTER_NAME: (( grab config.cluster.name ))
        WORKER_COUNT: (( grab config.cluster.worker-count))
      run:
        path: /usr/bin/env
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/gcp-create-cluster.sh" ))
