jobs:
- name: fast-forward-release
  plan:
  - get: eirini-release
    trigger: true
    passed:
    - run-eats-tests-((world-name))
    - (( concat "run-eats-tests-" config.gcp.cluster-name ))
  - get: eirini-release-master
  - put: eirini-release-master
    params:
      repository: eirini-release
