jobs:
- name: (( concat "run-eats-tests-" config.cluster.name ))
  public: true
  plan:
  - in_parallel:
      steps:
      - get: eirini-release
        passed:
        - verify-helm-deployment
        trigger: true
      - get: eirini
      - get: ci-resources
  - in_parallel:
      steps:
      - do:
        - task: download-kubeconfig
          config:
              platform: linux
              image_resource:
                type: docker-image
                source:
                  repository: eirini/ibmcloud
              inputs:
              - name:  ci-resources
              outputs:
              - name:  kube
              params:
                CLUSTER_NAME: (( grab config.cluster.name ))
                IBMCLOUD_ACCOUNT: (( grab config.ibmcloud.account ))
                IBMCLOUD_PASSWORD: (( grab config.ibmcloud.password ))
                IBMCLOUD_USER: (( grab config.ibmcloud.user ))
              run:
                path: /usr/bin/env
                args:
                - bash
                - -c
                - (( file "../../inline-tasks/download-kubeconfig.sh" ))
        - task: run-eats-tests
          privileged: true
          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: eirini/telepresence
            inputs:
            - name:  eirini
            - name:  kube
            outputs:
            - name:  output
            params:
                EIRINIUSER_PASSWORD: (( grab config.dockerhub.password ))
                KUBECONFIG: "kube/config"
            run:
              path: /usr/bin/env
              args:
              - bash
              - -c
              - (( file "../../inline-tasks/run-eats-tests.sh" ))
  on_failure: (( grab slack-notification.on_failure ))
