jobs:
- name: run-integration-tests
  public: true
  plan:
    - in_parallel:
      - get: kind-on-c
      - get: eirini
        trigger: true
        passed: [ run-tests ]
      - get: kind-release
        params:
          globs:
          - kind-linux-amd64
    - task: aggregate inputs for kind-on-c
      config:
        platform: linux
        image_resource:
          type: registry-image
          source: { repository: bash }
        inputs:
        - name: eirini
        outputs:
        - name: inputs # this will be the aggregated inputs for kind-on-c
        run:
          path: bash
          args:
          - -xeuc
          - |
            cp -a eirini inputs/
    - task: run-kind
      privileged: true
      file: kind-on-c/kind.yaml
      params:
        KIND_TESTS: |
          # your actual tests go here!
          kubectl get nodes -o wide

          mkdir -p /usr/local/go

          echo "Installing golang..."
          curl -sL "https://dl.google.com/go/go1.15.linux-amd64.tar.gz" --output /tmp/go.tar.gz
          tar xzf /tmp/go.tar.gz -C "/usr/local"
          rm /tmp/go.tar.gz

          echo "Installing ginkgo..."
          /usr/local/go/bin/go get -u "github.com/onsi/ginkgo/ginkgo"

          echo "Running tests..."
          cd inputs/eirini
          /usr/local/go/bin/go get -u "github.com/onsi/ginkgo/ginkgo"
          PATH=$PATH:$HOME/go/bin ./scripts/run_integration_tests.sh
  on_failure: (( grab slack-notification.on_failure ))

