jobs:
- name: verify-helm-deployment
  serial_groups:
  - helm-deployment
  plan:
  - get: ci-resources
  - get: cluster-state
  - get: eirini-release
    trigger: true
  - task: get-kubeconfig
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: eirini/ibmcloud
      inputs:
      - name: ci-resources
      outputs:
      - name: kube
      run:
        path: /usr/bin/env
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/download-kubeconfig.sh" ))
    params:
      CLUSTER_NAME: (( grab config.cluster.name ))
      IBMCLOUD_ACCOUNT: (( grab config.ibmcloud.account ))
      IBMCLOUD_PASSWORD: (( grab config.ibmcloud.password ))
      IBMCLOUD_USER: (( grab config.ibmcloud.user ))
  - task: deploy-eirini-bits
    config:
      platform: linux
      image_resource:
        source:
          repository: eirini/ibmcloud
        type: docker-image
      inputs:
      - name: kube
      - name: eirini-release
      - name: cluster-state
      params:
        CLUSTER_NAME: (( grab config.cluster.name ))
        NATS_PASSWORD: (( grab config.cluster.nats-password ))
        WIREMOCK_YAML: (( file "../../../eirini-release/helm/scripts/assets/wiremock.yml" ))
      run:
        path: /usr/bin/env
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/deploy-eirini-bits.sh" ))
  - task: verify-deployment
    config:
       platform: linux
       image_resource:
         type: docker-image
         source:
           repository: eirini/ibmcloud
       inputs:
       - name: kube
       run:
         path: /usr/bin/env
         args:
         - bash
         - -c
         - (( file "../../inline-tasks/verify-helm-deployment.sh" ))
  on_failure: (( grab slack-notification.on_failure ))
