#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/namespaces.star", "system_namespace", "workloads_namespace")

#@overlay/match by=overlay.subset({"kind": "Gateway", "metadata":{"name": "istio-ingressgateway"}})
---
spec:
  servers:
  #@overlay/match by=overlay.subset({"port":{"name":"https-workloads"}})
  - hosts:
    #@overlay/append
    - #@ workloads_namespace() + '/eirini.cf'
    tls:
      credentialName: eirinidotcf-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eirinidotcf-cert
  namespace: #@ system_namespace()
spec:
  secretName: eirinidotcf-cert
  commonName: eirini.cf
  dnsNames:
  - eirini.cf
  - #@ "*." + data.values.app_domains[0]
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: #@ system_namespace()
spec:
  acme:
    email: eirini@cloudfoundry.org
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: eirinidotcf-cert
    solvers:
    - http01:
        ingress:
          class: istio
