#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/namespaces.star", "system_namespace", "workloads_namespace")

#@overlay/match by=overlay.subset({"kind": "Gateway", "metadata":{"name": "istio-ingressgateway"}})
---
spec:
  servers:
  #@overlay/append
  - hosts:
    - #@ workloads_namespace() + '/eirini.cf'
    port:
      name: eirinidotcf-workload
      number: 443
      protocol: HTTPS
    tls:
      credentialName: eirinidotcf-cert
      mode: SIMPLE
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: eirinidotcf-cert
  namespace: #@ system_namespace()
spec:
  secretName: eirinidotcf-cert
  commonName: eirini.cf
  dnsNames:
  - eirini.cf
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: #@ system_namespace()
spec:
  acme:
    email: eirini@cloudfoundry.org
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: eirinidotcf-cert
    solvers:
    - http01:
        ingress:
          class: istio
